import One from "../images/room1.jpeg";
import Two from "../images/room2.jpeg";
import Three from "../images/room3.jpeg";
import Four from "../images/room4.jpeg";
import Five from "../images/room5.jpeg";
import Six from "../images/room6.jpeg";
const Data = [
  {
    id: 1,
    title: "Newly Built 3 bedroom flat at Justina Eze",
    details:
      "newly built 3 bedroom flat for rent at anthony village, standard and well furnished. Enough parking space, ",
    advantage: [
      "enough parking space",
      "well furnished",
      "good security system",
      "stable light",
      " wardrope",
    ],
    price: 350000,
    featured: true,
    condition: "newly built",
    ceiling: "POP",
    floor: "tiled",
    pictures: [One, Two, Three, Four, Five, Six],
  },
  {
    id: 2,
    title: "newly build single room at baracks",
    details:
      "newly built 3 bedroom flat for rent at anthony village, standard and well furnished. Enough parking space, ",
    advantage: [
      "enough parking space",
      "well furnished",
      "good security system",
      "stable light",
      " wardrope",
    ],
    price: 80000,
    featured: true,
    condition: "newly built",
    ceiling: "POP",
    floor: "tiled",
    pictures: [One, Two, Three, Four, Five, Six],
  },
  {
    id: 3,
    title: "2 bedroom flat at ofluonu",
    details:
      "newly built 3 bedroom flat for rent at anthony village, standard and well furnished. Enough parking space, ",
    advantage: [
      "enough parking space",
      "well furnished",
      "good security system",
      "stable light",
      " wardrope",
    ],
    price: 150000,
    featured: true,
    condition: "newly built",
    ceiling: "POP",
    floor: "tiled",
    pictures: [One, Two, Three, Four, Five, Six],
  },
  {
    id: 4,
    title: "new self contain at oloto 1",
    details:
      "newly built 3 bedroom flat for rent at anthony village, standard and well furnished. Enough parking space, ",
    advantage: [
      "enough parking space",
      "well furnished",
      "good security system",
      "stable light",
      " wardrope",
    ],
    price: 90000,
    featured: true,
    condition: "newly built",
    ceiling: "POP",
    floor: "tiled",
    pictures: [One, Two, Three, Four, Five, Six],
  },
  {
    id: 5,
    title: "single bedroom at slaughter road",
    details:
      "newly built 3 bedroom flat for rent at anthony village, standard and well furnished. Enough parking space, ",
    advantage: [
      "enough parking space",
      "well furnished",
      "good security system",
      "stable light",
      " wardrope",
    ],
    price: 50000,
    featured: true,
    condition: "newly built",
    ceiling: "POP",
    floor: "tiled",
    pictures: [One, Two, Three, Four, Five, Six],
  },
  {
    id: 6,
    title: "2 room shop at enugu road",
    details:
      "newly built 3 bedroom flat for rent at anthony village, standard and well furnished. Enough parking space, ",
    advantage: [
      "enough parking space",
      "well furnished",
      "good security system",
      "stable light",
      " wardrope",
    ],
    price: 50000,
    featured: true,
    condition: "newly built",
    ceiling: "POP",
    floor: "tiled",
    pictures: [One, Two, Three, Four, Five, Six],
  },
  {
    id: 7,
    title: "3 bedroom flat at orba junction",
    details:
      "newly built 3 bedroom flat for rent at anthony village, standard and well furnished. Enough parking space, ",
    advantage: [
      "enough parking space",
      "well furnished",
      "good security system",
      "stable light",
      " wardrope",
    ],
    price: 250000,
    featured: true,
    condition: "newly built",
    ceiling: "POP",
    floor: "tiled",
    pictures: [One, Two, Three, Four, Five, Six],
  },
  {
    id: 8,
    title: "self contain beside unn gate",
    details:
      "newly built 3 bedroom flat for rent at anthony village, standard and well furnished. Enough parking space, ",
    advantage: [
      "enough parking space",
      "well furnished",
      "good security system",
      "stable light",
      " wardrope",
    ],
    price: 150000,
    featured: false,
    condition: "newly built",
    ceiling: "POP",
    floor: "tiled",
    pictures: [One, Two, Three, Four, Five, Six],
  },
  {
    id: 9,
    title: "single room at unn second gate",
    details:
      "newly built 3 bedroom flat for rent at anthony village, standard and well furnished. Enough parking space, ",
    advantage: [
      "enough parking space",
      "well furnished",
      "good security system",
      "stable light",
      " wardrope",
    ],
    price: 70000,
    featured: true,
    condition: "newly built",
    ceiling: "POP",
    floor: "tiled",
    pictures: [One, Two, Three, Four, Five, Six],
  },
  {
    id: 10,
    title: "2 bedrrrom flat at onuiyi",
    details:
      "newly built 3 bedroom flat for rent at anthony village, standard and well furnished. Enough parking space, ",
    advantage: [
      "enough parking space",
      "well furnished",
      "good security system",
      "stable light",
      " wardrope",
    ],
    price: 200000,
    featured: true,
    condition: "newly built",
    ceiling: "POP",
    floor: "tiled",
    pictures: [One, Two, Three, Four, Five, Six],
  },
  {
    id: 11,
    title: "self contain opposite bestie indomie",
    details:
      "newly built 3 bedroom flat for rent at anthony village, standard and well furnished. Enough parking space, ",
    advantage: [
      "enough parking space",
      "well furnished",
      "good security system",
      "stable light",
      " wardrope",
    ],
    price: 50000,
    featured: false,
    condition: "newly built",
    ceiling: "POP",
    floor: "tiled",
    pictures: [One, Two, Three, Four, Five, Six],
  },
  {
    id: 12,
    title: "2 bedroom flat at total round about",
    details:
      "newly built 3 bedroom flat for rent at anthony village, standard and well furnished. Enough parking space, ",
    advantage: [
      "enough parking space",
      "well furnished",
      "good security system",
      "stable light",
      " wardrope",
    ],
    price: 200000,
    featured: true,
    condition: "newly built",
    ceiling: "POP",
    floor: "tiled",
    pictures: [One, Two, Three, Four, Five, Six],
  },
];

export default Data;
