const Locations = {
  nsukka: [
    "Alor-Uno",
    "Edem",
    "Ede-Oballa",
    "Eha Alumona",
    "Eha Ndiagu",
    "Ibagwani",
    "Ibagwa-Agu Awka",
    "Obimo",
    "Obukpa",
    "Okpaligbo",
    "Okpuje",
    "Okutu",
    "Opi",
    "Opi-Agu",
    "Lejja",
    "Umuabor",
  ],
  udenu: [
    "Umundu",
    "Orba",
    "Obgodu Aba",
    "Obollo-Etiti",
    "Obollo-Eke",
    "Imilike-Uno",
    "Imilike-Agu",
    "Ezimo-Agu",
    "Ezimo-Uno",
    "Obollo-Afor",
    "Amalla",
  ],

  igboEtiti: ["ukehe", "Ekwegbe", "Ozalla", "Ohodo", "Aku", "Ohebedim"],
  uzoUwani: [
    "Adaba",
    "Abii",
    "Nrobo",
    "Ugbene",
    "Nkpologu",
    "Ogurugu",
    "Akpugu-Ezedike",
    "Nkume",
    "Ukpata",
    "Umulokpa",
    "Ojor",
    "Igga",
    "Adani",
    "Uvuru",
    "Nimbo",
  ],
  igboEzeNorth: ["Enugu-Ezike", "Ette"],
  igboEzeSouth: [
    "Uhunowerre",
    "Alor Agu",
    "Ibagwa-Aka",
    "Iheakpu Awka",
    "Ovoko Ulo",
    "Ovoko Agu",
    "Iheaka",
    "Unadu",
    "Nkalagu-Obukpa",
    "Itchi",
  ],
};

export default Locations;
